version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: timesheet-postgres
    environment:
      POSTGRES_DB: timesheet_db
      POSTGRES_USER: your_user
      POSTGRES_PASSWORD: your_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - timesheet-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: timesheet-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/timesheet_db
      SPRING_DATASOURCE_USERNAME: postyour_user
      SPRING_DATASOURCE_PASSWORD: your_password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - timesheet-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: timesheet-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - timesheet-network

volumes:
  postgres_data:

networks:
  timesheet-network:
    driver: bridge